### ISSUE TITLE
Panic when a struct has pointers to other structs

### ISSUE THREAD

**Issue by resokou** [mashingan/smapping#8]
I tested it with the function `MapTags`:
```
reflect: call of reflect.Value.NumField on ptr Value
C:/Program Files/Go/src/reflect/value.go:223 (0xffe54c)
        flag.mustBe: panic(&ValueError{methodName(), f.kind()})
C:/Program Files/Go/src/reflect/value.go:1891 (0xffe4e2)
        Value.NumField: v.mustBe(Struct)
C:/Users/Power/go/pkg/mod/github.com/mashingan/smapping@v0.1.16/smapping.go:128 (0x1751264)
        MapTags: for i := 0; i < value.NumField(); i++ {
```

It seems before calling `value.NumField()` it must be ensured `value` is not a pointer. I tried to modify the code with something like this and it seemed to work:

```golang
func MapTags(x interface{}, tag string) Mapped {
	result := make(Mapped)
	vvalue := extractValue(x)
	if !vvalue.IsValid() {
		return nil
	}

	var value reflect.Value
	if vvalue.Kind() == reflect.Ptr {
		value = vvalue.Elem()
	} else {
		value = vvalue
	}
	xtype := value.Type()

	for i := 0; i < value.NumField(); i++ {
```

**Comment by mashingan** [comment]
Hmm, could you also check this test? https://github.com/mashingan/smapping/blob/master/smapping_test.go#L200-L268 . You can try to modify all the nested object with pointer.  
While your change is indeed the fix, I wanna know why the test was success but failed in your case.

**Comment by resokou** [comment]
Thanks for the quick reply. It seems it's a mistake on my part. I double checked my code when trying to recreate the issue on a smaller scale and noticed my functions returned a pointer to a struct and I was mistakenly de-referencing it a second time when calling the smapping API. So I was effectively doing something like:
```golang
Function(...) *Entity

r := Function(...)
smapping.MapFields(&r)
```
Just under a few layers of API calls. My bad. I should've double checked my code and mistakenly assumed it was a problem with some nested struct pointers I had instead.

I also checked the tests included in this library and they all pass without any problem.

**Comment by mashingan** [comment]
Ah, no worries. I'm glad it's not actually bug. But going to change its internal to leniently accepting (zero or many pointers to) struct for Map functions.  
With this change, even if it's `***Struct`, should be no problem to get its mapping values.
